[#IOPID-757] logout endpoint
pagopa/io-functions-fast-login pull request #17
Opened 2023-09-26 15:30 UTC by arcogabbo

#### List of Changes

* logout endpoint

#### Motivation and Context

introduce a new endpoint

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2023-09-26 16:00 UTC, BurnedMarshal requested changes

2023-09-26 16:00 UTC, BurnedMarshal commented on README.md
> +| BACKEND_INTERNAL_BASE_URL          | API Url for `logout` operation               | string |
Add these variables if missing in infra of the function

2023-09-26 16:00 UTC, BurnedMarshal commented on src/functions/logout.ts
> +          );
Can we use a `fromPredicate` instead of a two option case? Nevertheless it will map automatically right and left scenario.

2023-09-26 16:00 UTC, BurnedMarshal commented on src/functions/logout.ts
> +  H.HttpResponse<null, 200>,
What if we change to `204 No Content` ?

2023-09-26 16:00 UTC, BurnedMarshal commented on src/middlewares/__tests__/request.test.ts
> +    ${{ fiscalcode: "", sample: aValidPayload.sample }}
Add a test with a non empty wrong `fiscalCode`

2023-09-27 07:38 UTC, arcogabbo commented on README.md
> +| BACKEND_INTERNAL_BASE_URL          | API Url for `logout` operation               | string |
thank you. the relative PR is https://github.com/pagopa/io-infra/pull/690

2023-09-27 08:07 UTC, arcogabbo commented on src/functions/logout.ts
> +          );
nice suggestion. applied in https://github.com/pagopa/io-functions-fast-login/pull/17/commits/1c1dc8ff8b69c83ebd5cc6468443c23b2beea5e2

2023-09-27 08:07 UTC, arcogabbo commented on src/middlewares/__tests__/request.test.ts
> +    ${{ fiscalcode: "", sample: aValidPayload.sample }}
applied in https://github.com/pagopa/io-functions-fast-login/pull/17/commits/6f602199ae9c34bb5776201e57d468f13af8c49f

2023-09-27 08:21 UTC, arcogabbo commented on src/functions/logout.ts
> +  H.HttpResponse<null, 200>,
applied in https://github.com/pagopa/io-functions-fast-login/pull/17/commits/cd3fa6cfb50a4694b6f3d09f58eec1c1ca8567dd

2023-09-28 08:59 UTC, gquadrati approved these changes
LGTM

2023-09-28 09:13 UTC, BurnedMarshal approved these changes
LGTM

2023-09-28 09:14 UTC, merged